# Copyright (C) 2024 SUSE LLC <petr.pavlu@suse.com>
# SPDX-License-Identifier: GPL-2.0-or-later

[package]
name = "suse-kabi-tools"
authors = ["Petr Pavlu <petr.pavlu@suse.com>"]
edition = "2024"
rust-version = "1.88"
