# Copyright (C) 2024 SUSE LLC <petr.pavlu@suse.com>
# SPDX-License-Identifier: GPL-2.0-or-later

[package]
name = "ksyms"
version = "0.1.0"
authors = ["Petr Pavlu <petr.pavlu@suse.com>"]
edition = "2021"

[dependencies]
diffs = "0.5.1"
env_logger = "0.11.1"
log = "0.4.20"
