Export 'nf_flow_register_bpf' has been removed
Export 'vsc_tp_free_irq' has been removed
Export 'vsc_tp_request_irq' has been removed
Export 'xfrm_bpf_md_dst' has been removed
The following '193' exports are different:
 ____kvm_emulate_hypercall
 __gfn_to_page
 __kvm_prepare_emulation_failure_exit
 __kvm_vcpu_map
 __kvm_vcpu_update_apicv
 __traceiter_kvm_entry
 __traceiter_kvm_exit
 __traceiter_kvm_nested_vmexit
 __traceiter_kvm_page_fault
 __traceiter_kvm_rmp_fault
 <...>

because of a changed 'E#NR_KVM_CPU_CAPS':
@@ -1,1 +1,1 @@
-( 25 ) + 6
+( 25 ) + 7

The following '9' exports are different:
 mana_gd_create_mana_eq
 mana_gd_create_mana_wq_cq
 mana_gd_destroy_dma_region
 mana_gd_destroy_queue
 mana_gd_poll_cq
 mana_gd_post_work_request
 mana_gd_ring_cq
 mana_gd_send_request
 mana_gd_wq_ring_doorbell

because 's#device_node' changed from a forward declaration to a definition

The following '14' exports are different:
 mana_cfg_vport
 mana_create_wq_obj
 mana_destroy_wq_obj
 mana_gd_create_mana_eq
 mana_gd_create_mana_wq_cq
 mana_gd_destroy_dma_region
 mana_gd_destroy_queue
 mana_gd_poll_cq
 mana_gd_post_work_request
 mana_gd_ring_cq
 <...>

because of a changed 's#gdma_context':
@@ -4,7 +4,7 @@
 	unsigned int max_num_queues;
 	unsigned int max_num_msix;
 	unsigned int num_msix_usable;
-	s#gdma_irq_context * irq_contexts;
+	s#xarray irq_contexts;
 	t#u16 adapter_mtu;
 	unsigned int max_num_cqs;
 	s#gdma_queue * * cq_table;
@@ -12,6 +12,7 @@
 	s#completion eq_test_event;
 	t#u32 test_event_eq_id;
 	t#bool is_pf;
+	t#bool in_service;
 	t#phys_addr_t bar0_pa;
 	void * bar0_va;
 	void * shm_base;

The following '5' exports are different:
 ice_add_rdma_qset
 ice_del_rdma_qset
 ice_get_qos_params
 ice_rdma_request_reset
 ice_rdma_update_vsi_filter

because of a changed 's#ice_pf':
@@ -7,9 +7,7 @@
 	s#devlink_port devlink_port;
 	s#msix_entry * msix_entries;
 	s#ice_irq_tracker irq_tracker;
-	t#u16 sriov_base_vector;
-	unsigned long * sriov_irq_bm;
-	t#u16 sriov_irq_size;
+	s#ice_virt_irq_tracker virt_irq_tracker;
 	t#u16 ctrl_vsi_idx;
 	s#ice_vsi * * vsi;
 	s#ice_vsi_stats * * vsi_stats;
@@ -52,7 +50,7 @@
 	s#msi_map ll_ts_irq;
 	t#u16 max_pf_txqs;
 	t#u16 max_pf_rxqs;
-	t#u16 num_lan_msix;
+	s#ice_pf_msix msix;
 	t#u16 num_lan_tx;
 	t#u16 num_lan_rx;
 	t#u16 next_vsi;

The following '9' exports are different:
 mana_gd_create_mana_eq
 mana_gd_create_mana_wq_cq
 mana_gd_destroy_dma_region
 mana_gd_destroy_queue
 mana_gd_poll_cq
 mana_gd_post_work_request
 mana_gd_ring_cq
 mana_gd_send_request
 mana_gd_wq_ring_doorbell

because 's#irq_domain' changed from a forward declaration to a definition

The following '4' exports are different:
 mana_cfg_vport
 mana_create_wq_obj
 mana_destroy_wq_obj
 mana_uncfg_vport

because of a changed 's#mana_port_context':
@@ -27,9 +27,13 @@
 	t#mana_handle_t pf_filter_handle;
 	s#mutex vport_mutex;
 	int vport_use_count;
+	s#net_shaper_handle handle;
 	t#u16 port_idx;
+	t#u32 speed;
+	t#u32 max_speed;
 	t#bool port_is_up;
 	t#bool port_st_save;
 	s#mana_ethtool_stats eth_stats;
+	s#mana_ethtool_phy_stats phy_stats;
 	s#dentry * mana_port_debugfs;
 }

The following '14' exports are different:
 mana_cfg_vport
 mana_create_wq_obj
 mana_destroy_wq_obj
 mana_gd_create_mana_eq
 mana_gd_create_mana_wq_cq
 mana_gd_destroy_dma_region
 mana_gd_destroy_queue
 mana_gd_poll_cq
 mana_gd_post_work_request
 mana_gd_ring_cq
 <...>

because 's#net_shaper_ops' changed from a forward declaration to a definition

The following '3' exports are different:
 __traceiter_smc_rx_recvmsg
 __traceiter_smc_switch_to_fallback
 __traceiter_smc_tx_sendmsg

because of a changed 's#smc_sock':
@@ -1,6 +1,8 @@
 struct smc_sock {
-	s#sock sk;
-	s#ipv6_pinfo * pinet6;
+	union {
+		s#sock sk;
+		s#inet_sock icsk_inet;
+	};
 	s#socket * clcsock;
 	void ( * clcsk_state_change ) ( s#sock * );
 	void ( * clcsk_data_ready ) ( s#sock * );
