.\" Copyright (C) 2024-2025 SUSE LLC <petr.pavlu@suse.com>
.\" SPDX-License-Identifier: GPL-2.0-or-later
.TH KSYMVERS 1
.SH NAME
ksymvers \- a tool to work with Linux\-kernel symvers files
.SH SYNOPSIS
\fBksymvers\fR [\fIGENERAL\-OPTION\fR...] { \fBcompare\fR } [\fICOMMAND\-OPTION\fR...] ...
.SH DESCRIPTION
TODO
.SH GENERAL OPTIONS
.TP
\fB\-d\fR, \fB\-\-debug\fR
Enable debug output.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display global help information and exit.
.TP
\fB\-\-version\fR
Output version information and exit.
.SH COMPARE COMMAND
\fBksymvers\fR \fBcompare\fR [\fICOMPARE\-OPTION\fR...] \fIFILE\fR \fIFILE2\fR
.PP
TODO
.PP
Available options:
.TP
\fB\-h\fR, \fB\-\-help\fR
Display help information for the command and exit.
.SH EXAMPLES
TODO
.SH SEE ALSO
\fBksymtypes\fR(1), \fBsuse-kabi-tools\fR(5)
